apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels: 
    app: ubuntu-test
spec:
  volumes:
    - name: postgresql-cert-volume
      secret:
        secretName: postgresql-ssl
        defaultMode: 0600 
  containers:
  - name: ubuntu
    image: ubuntu:24.04
    command: ['/bin/sh', '-c']
    args:
      - apt-get update && apt-get install -y postgresql-client;
        sleep infinity; 
    volumeMounts:
      - name: postgresql-cert-volume
        mountPath: '/root/.postgresql'

