apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django-app
spec:
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - image: usernameart/django_app:latest
        imagePullPolicy: IfNotPresent
        name: django-deploy
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: django-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  type: NodePort
  selector:
    app: django-app
  ports:
    - port: 80
      targetPort: 80
