apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - image: usernameart/django_app
        imagePullPolicy: IfNotPresent
        name: django
        ports:
        - containerPort: 80
        env:
        - name: DEBUG
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DEBUG
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: SECRET_KEY
        - name: ALLOWED_HOSTS
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: ALLOWED_HOSTS

---
apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  type: NodePort
  selector:
    app: django-app
  ports:
    - port: 80
      targetPort: 
      nodePort: 30007
